// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/v1/review.proto

package review

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RideId        string                 `protobuf:"bytes,2,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	FromUserId    string                 `protobuf:"bytes,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      string                 `protobuf:"bytes,4,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Score         int32                  `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"` // 1-5 rating
	Comment       string                 `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Server-assigned
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_proto_v1_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_proto_v1_review_proto_rawDescGZIP(), []int{0}
}

func (x *Review) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Review) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *Review) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *Review) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *Review) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Review) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Review) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// SubmitReview
type SubmitReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"` //Provide ride_id, from_user_id, to_user_id, score, comment, Server sets id and created_at
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitReviewRequest) Reset() {
	*x = SubmitReviewRequest{}
	mi := &file_proto_v1_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitReviewRequest) ProtoMessage() {}

func (x *SubmitReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitReviewRequest.ProtoReflect.Descriptor instead.
func (*SubmitReviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_review_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitReviewRequest) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type SubmitReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"` //Review along with id and created_at
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitReviewResponse) Reset() {
	*x = SubmitReviewResponse{}
	mi := &file_proto_v1_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitReviewResponse) ProtoMessage() {}

func (x *SubmitReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitReviewResponse.ProtoReflect.Descriptor instead.
func (*SubmitReviewResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_review_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitReviewResponse) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

// ListReviewsByUser
type ListReviewsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsByUserRequest) Reset() {
	*x = ListReviewsByUserRequest{}
	mi := &file_proto_v1_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsByUserRequest) ProtoMessage() {}

func (x *ListReviewsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsByUserRequest.ProtoReflect.Descriptor instead.
func (*ListReviewsByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_review_proto_rawDescGZIP(), []int{3}
}

func (x *ListReviewsByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListReviewsByUserRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListReviewsByUserRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListReviewsByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsByUserResponse) Reset() {
	*x = ListReviewsByUserResponse{}
	mi := &file_proto_v1_review_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsByUserResponse) ProtoMessage() {}

func (x *ListReviewsByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_review_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsByUserResponse.ProtoReflect.Descriptor instead.
func (*ListReviewsByUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_review_proto_rawDescGZIP(), []int{4}
}

func (x *ListReviewsByUserResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

// ListReviewsByRide
type ListReviewsByRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsByRideRequest) Reset() {
	*x = ListReviewsByRideRequest{}
	mi := &file_proto_v1_review_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsByRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsByRideRequest) ProtoMessage() {}

func (x *ListReviewsByRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_review_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsByRideRequest.ProtoReflect.Descriptor instead.
func (*ListReviewsByRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_review_proto_rawDescGZIP(), []int{5}
}

func (x *ListReviewsByRideRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

type ListReviewsByRideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsByRideResponse) Reset() {
	*x = ListReviewsByRideResponse{}
	mi := &file_proto_v1_review_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsByRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsByRideResponse) ProtoMessage() {}

func (x *ListReviewsByRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_review_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsByRideResponse.ProtoReflect.Descriptor instead.
func (*ListReviewsByRideResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_review_proto_rawDescGZIP(), []int{6}
}

func (x *ListReviewsByRideResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

// DeleteReview
type DeleteReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      string                 `protobuf:"bytes,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewRequest) Reset() {
	*x = DeleteReviewRequest{}
	mi := &file_proto_v1_review_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewRequest) ProtoMessage() {}

func (x *DeleteReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_review_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewRequest.ProtoReflect.Descriptor instead.
func (*DeleteReviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_review_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteReviewRequest) GetReviewId() string {
	if x != nil {
		return x.ReviewId
	}
	return ""
}

type DeleteReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewResponse) Reset() {
	*x = DeleteReviewResponse{}
	mi := &file_proto_v1_review_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewResponse) ProtoMessage() {}

func (x *DeleteReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_review_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewResponse.ProtoReflect.Descriptor instead.
func (*DeleteReviewResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_review_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteReviewResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_v1_review_proto protoreflect.FileDescriptor

const file_proto_v1_review_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/review.proto\x12\bproto.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x01\n" +
	"\x06Review\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aride_id\x18\x02 \x01(\tR\x06rideId\x12 \n" +
	"\ffrom_user_id\x18\x03 \x01(\tR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x04 \x01(\tR\btoUserId\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x05R\x05score\x12\x18\n" +
	"\acomment\x18\x06 \x01(\tR\acomment\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"?\n" +
	"\x13SubmitReviewRequest\x12(\n" +
	"\x06review\x18\x01 \x01(\v2\x10.proto.v1.ReviewR\x06review\"@\n" +
	"\x14SubmitReviewResponse\x12(\n" +
	"\x06review\x18\x01 \x01(\v2\x10.proto.v1.ReviewR\x06review\"a\n" +
	"\x18ListReviewsByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"G\n" +
	"\x19ListReviewsByUserResponse\x12*\n" +
	"\areviews\x18\x01 \x03(\v2\x10.proto.v1.ReviewR\areviews\"3\n" +
	"\x18ListReviewsByRideRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\"G\n" +
	"\x19ListReviewsByRideResponse\x12*\n" +
	"\areviews\x18\x01 \x03(\v2\x10.proto.v1.ReviewR\areviews\"2\n" +
	"\x13DeleteReviewRequest\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\tR\breviewId\"0\n" +
	"\x14DeleteReviewResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf1\x02\n" +
	"\rReviewService\x12O\n" +
	"\fSubmitReview\x12\x1d.proto.v1.SubmitReviewRequest\x1a\x1e.proto.v1.SubmitReviewResponse\"\x00\x12^\n" +
	"\x11ListReviewsByUser\x12\".proto.v1.ListReviewsByUserRequest\x1a#.proto.v1.ListReviewsByUserResponse\"\x00\x12^\n" +
	"\x11ListReviewsByRide\x12\".proto.v1.ListReviewsByRideRequest\x1a#.proto.v1.ListReviewsByRideResponse\"\x00\x12O\n" +
	"\fDeleteReview\x12\x1d.proto.v1.DeleteReviewRequest\x1a\x1e.proto.v1.DeleteReviewResponse\"\x00B\x13Z\x11./proto/v1/reviewb\x06proto3"

var (
	file_proto_v1_review_proto_rawDescOnce sync.Once
	file_proto_v1_review_proto_rawDescData []byte
)

func file_proto_v1_review_proto_rawDescGZIP() []byte {
	file_proto_v1_review_proto_rawDescOnce.Do(func() {
		file_proto_v1_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_review_proto_rawDesc), len(file_proto_v1_review_proto_rawDesc)))
	})
	return file_proto_v1_review_proto_rawDescData
}

var file_proto_v1_review_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_v1_review_proto_goTypes = []any{
	(*Review)(nil),                    // 0: proto.v1.Review
	(*SubmitReviewRequest)(nil),       // 1: proto.v1.SubmitReviewRequest
	(*SubmitReviewResponse)(nil),      // 2: proto.v1.SubmitReviewResponse
	(*ListReviewsByUserRequest)(nil),  // 3: proto.v1.ListReviewsByUserRequest
	(*ListReviewsByUserResponse)(nil), // 4: proto.v1.ListReviewsByUserResponse
	(*ListReviewsByRideRequest)(nil),  // 5: proto.v1.ListReviewsByRideRequest
	(*ListReviewsByRideResponse)(nil), // 6: proto.v1.ListReviewsByRideResponse
	(*DeleteReviewRequest)(nil),       // 7: proto.v1.DeleteReviewRequest
	(*DeleteReviewResponse)(nil),      // 8: proto.v1.DeleteReviewResponse
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
}
var file_proto_v1_review_proto_depIdxs = []int32{
	9, // 0: proto.v1.Review.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: proto.v1.SubmitReviewRequest.review:type_name -> proto.v1.Review
	0, // 2: proto.v1.SubmitReviewResponse.review:type_name -> proto.v1.Review
	0, // 3: proto.v1.ListReviewsByUserResponse.reviews:type_name -> proto.v1.Review
	0, // 4: proto.v1.ListReviewsByRideResponse.reviews:type_name -> proto.v1.Review
	1, // 5: proto.v1.ReviewService.SubmitReview:input_type -> proto.v1.SubmitReviewRequest
	3, // 6: proto.v1.ReviewService.ListReviewsByUser:input_type -> proto.v1.ListReviewsByUserRequest
	5, // 7: proto.v1.ReviewService.ListReviewsByRide:input_type -> proto.v1.ListReviewsByRideRequest
	7, // 8: proto.v1.ReviewService.DeleteReview:input_type -> proto.v1.DeleteReviewRequest
	2, // 9: proto.v1.ReviewService.SubmitReview:output_type -> proto.v1.SubmitReviewResponse
	4, // 10: proto.v1.ReviewService.ListReviewsByUser:output_type -> proto.v1.ListReviewsByUserResponse
	6, // 11: proto.v1.ReviewService.ListReviewsByRide:output_type -> proto.v1.ListReviewsByRideResponse
	8, // 12: proto.v1.ReviewService.DeleteReview:output_type -> proto.v1.DeleteReviewResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_v1_review_proto_init() }
func file_proto_v1_review_proto_init() {
	if File_proto_v1_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_review_proto_rawDesc), len(file_proto_v1_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_review_proto_goTypes,
		DependencyIndexes: file_proto_v1_review_proto_depIdxs,
		MessageInfos:      file_proto_v1_review_proto_msgTypes,
	}.Build()
	File_proto_v1_review_proto = out.File
	file_proto_v1_review_proto_goTypes = nil
	file_proto_v1_review_proto_depIdxs = nil
}
