// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/v1/location.proto

package location

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Geohash       string                 `protobuf:"bytes,4,opt,name=geohash,proto3" json:"geohash,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLocation) Reset() {
	*x = UserLocation{}
	mi := &file_proto_v1_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLocation) ProtoMessage() {}

func (x *UserLocation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLocation.ProtoReflect.Descriptor instead.
func (*UserLocation) Descriptor() ([]byte, []int) {
	return file_proto_v1_location_proto_rawDescGZIP(), []int{0}
}

func (x *UserLocation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserLocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UserLocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UserLocation) GetGeohash() string {
	if x != nil {
		return x.Geohash
	}
	return ""
}

func (x *UserLocation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UpsertLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Geohash       string                 `protobuf:"bytes,3,opt,name=geohash,proto3" json:"geohash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertLocationRequest) Reset() {
	*x = UpsertLocationRequest{}
	mi := &file_proto_v1_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertLocationRequest) ProtoMessage() {}

func (x *UpsertLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertLocationRequest.ProtoReflect.Descriptor instead.
func (*UpsertLocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_location_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertLocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpsertLocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UpsertLocationRequest) GetGeohash() string {
	if x != nil {
		return x.Geohash
	}
	return ""
}

type UpsertLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *UserLocation          `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertLocationResponse) Reset() {
	*x = UpsertLocationResponse{}
	mi := &file_proto_v1_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertLocationResponse) ProtoMessage() {}

func (x *UpsertLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertLocationResponse.ProtoReflect.Descriptor instead.
func (*UpsertLocationResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_location_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertLocationResponse) GetLocation() *UserLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

type GetLocationByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationByUserRequest) Reset() {
	*x = GetLocationByUserRequest{}
	mi := &file_proto_v1_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationByUserRequest) ProtoMessage() {}

func (x *GetLocationByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationByUserRequest.ProtoReflect.Descriptor instead.
func (*GetLocationByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_location_proto_rawDescGZIP(), []int{3}
}

func (x *GetLocationByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetLocationByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *UserLocation          `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationByUserResponse) Reset() {
	*x = GetLocationByUserResponse{}
	mi := &file_proto_v1_location_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationByUserResponse) ProtoMessage() {}

func (x *GetLocationByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_location_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationByUserResponse.ProtoReflect.Descriptor instead.
func (*GetLocationByUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_location_proto_rawDescGZIP(), []int{4}
}

func (x *GetLocationByUserResponse) GetLocation() *UserLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

type ListNearbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GeohashPrefix string                 `protobuf:"bytes,1,opt,name=geohash_prefix,json=geohashPrefix,proto3" json:"geohash_prefix,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNearbyRequest) Reset() {
	*x = ListNearbyRequest{}
	mi := &file_proto_v1_location_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNearbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNearbyRequest) ProtoMessage() {}

func (x *ListNearbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_location_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNearbyRequest.ProtoReflect.Descriptor instead.
func (*ListNearbyRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_location_proto_rawDescGZIP(), []int{5}
}

func (x *ListNearbyRequest) GetGeohashPrefix() string {
	if x != nil {
		return x.GeohashPrefix
	}
	return ""
}

func (x *ListNearbyRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListNearbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*UserLocation        `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNearbyResponse) Reset() {
	*x = ListNearbyResponse{}
	mi := &file_proto_v1_location_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNearbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNearbyResponse) ProtoMessage() {}

func (x *ListNearbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_location_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNearbyResponse.ProtoReflect.Descriptor instead.
func (*ListNearbyResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_location_proto_rawDescGZIP(), []int{6}
}

func (x *ListNearbyResponse) GetLocations() []*UserLocation {
	if x != nil {
		return x.Locations
	}
	return nil
}

type DeleteMyLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMyLocationRequest) Reset() {
	*x = DeleteMyLocationRequest{}
	mi := &file_proto_v1_location_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMyLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMyLocationRequest) ProtoMessage() {}

func (x *DeleteMyLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_location_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMyLocationRequest.ProtoReflect.Descriptor instead.
func (*DeleteMyLocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_location_proto_rawDescGZIP(), []int{7}
}

type DeleteMyLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMyLocationResponse) Reset() {
	*x = DeleteMyLocationResponse{}
	mi := &file_proto_v1_location_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMyLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMyLocationResponse) ProtoMessage() {}

func (x *DeleteMyLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_location_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMyLocationResponse.ProtoReflect.Descriptor instead.
func (*DeleteMyLocationResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_location_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMyLocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_v1_location_proto protoreflect.FileDescriptor

const file_proto_v1_location_proto_rawDesc = "" +
	"\n" +
	"\x17proto/v1/location.proto\x12\bproto.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb6\x01\n" +
	"\fUserLocation\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x18\n" +
	"\ageohash\x18\x04 \x01(\tR\ageohash\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"k\n" +
	"\x15UpsertLocationRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x18\n" +
	"\ageohash\x18\x03 \x01(\tR\ageohash\"L\n" +
	"\x16UpsertLocationResponse\x122\n" +
	"\blocation\x18\x01 \x01(\v2\x16.proto.v1.UserLocationR\blocation\"3\n" +
	"\x18GetLocationByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"O\n" +
	"\x19GetLocationByUserResponse\x122\n" +
	"\blocation\x18\x01 \x01(\v2\x16.proto.v1.UserLocationR\blocation\"P\n" +
	"\x11ListNearbyRequest\x12%\n" +
	"\x0egeohash_prefix\x18\x01 \x01(\tR\rgeohashPrefix\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"J\n" +
	"\x12ListNearbyResponse\x124\n" +
	"\tlocations\x18\x01 \x03(\v2\x16.proto.v1.UserLocationR\tlocations\"\x19\n" +
	"\x17DeleteMyLocationRequest\"4\n" +
	"\x18DeleteMyLocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf0\x02\n" +
	"\x0fLocationService\x12U\n" +
	"\x0eUpsertLocation\x12\x1f.proto.v1.UpsertLocationRequest\x1a .proto.v1.UpsertLocationResponse\"\x00\x12^\n" +
	"\x11GetLocationByUser\x12\".proto.v1.GetLocationByUserRequest\x1a#.proto.v1.GetLocationByUserResponse\"\x00\x12I\n" +
	"\n" +
	"ListNearby\x12\x1b.proto.v1.ListNearbyRequest\x1a\x1c.proto.v1.ListNearbyResponse\"\x00\x12[\n" +
	"\x10DeleteMyLocation\x12!.proto.v1.DeleteMyLocationRequest\x1a\".proto.v1.DeleteMyLocationResponse\"\x00B\x15Z\x13./proto/v1/locationb\x06proto3"

var (
	file_proto_v1_location_proto_rawDescOnce sync.Once
	file_proto_v1_location_proto_rawDescData []byte
)

func file_proto_v1_location_proto_rawDescGZIP() []byte {
	file_proto_v1_location_proto_rawDescOnce.Do(func() {
		file_proto_v1_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_location_proto_rawDesc), len(file_proto_v1_location_proto_rawDesc)))
	})
	return file_proto_v1_location_proto_rawDescData
}

var file_proto_v1_location_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_v1_location_proto_goTypes = []any{
	(*UserLocation)(nil),              // 0: proto.v1.UserLocation
	(*UpsertLocationRequest)(nil),     // 1: proto.v1.UpsertLocationRequest
	(*UpsertLocationResponse)(nil),    // 2: proto.v1.UpsertLocationResponse
	(*GetLocationByUserRequest)(nil),  // 3: proto.v1.GetLocationByUserRequest
	(*GetLocationByUserResponse)(nil), // 4: proto.v1.GetLocationByUserResponse
	(*ListNearbyRequest)(nil),         // 5: proto.v1.ListNearbyRequest
	(*ListNearbyResponse)(nil),        // 6: proto.v1.ListNearbyResponse
	(*DeleteMyLocationRequest)(nil),   // 7: proto.v1.DeleteMyLocationRequest
	(*DeleteMyLocationResponse)(nil),  // 8: proto.v1.DeleteMyLocationResponse
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
}
var file_proto_v1_location_proto_depIdxs = []int32{
	9, // 0: proto.v1.UserLocation.updated_at:type_name -> google.protobuf.Timestamp
	0, // 1: proto.v1.UpsertLocationResponse.location:type_name -> proto.v1.UserLocation
	0, // 2: proto.v1.GetLocationByUserResponse.location:type_name -> proto.v1.UserLocation
	0, // 3: proto.v1.ListNearbyResponse.locations:type_name -> proto.v1.UserLocation
	1, // 4: proto.v1.LocationService.UpsertLocation:input_type -> proto.v1.UpsertLocationRequest
	3, // 5: proto.v1.LocationService.GetLocationByUser:input_type -> proto.v1.GetLocationByUserRequest
	5, // 6: proto.v1.LocationService.ListNearby:input_type -> proto.v1.ListNearbyRequest
	7, // 7: proto.v1.LocationService.DeleteMyLocation:input_type -> proto.v1.DeleteMyLocationRequest
	2, // 8: proto.v1.LocationService.UpsertLocation:output_type -> proto.v1.UpsertLocationResponse
	4, // 9: proto.v1.LocationService.GetLocationByUser:output_type -> proto.v1.GetLocationByUserResponse
	6, // 10: proto.v1.LocationService.ListNearby:output_type -> proto.v1.ListNearbyResponse
	8, // 11: proto.v1.LocationService.DeleteMyLocation:output_type -> proto.v1.DeleteMyLocationResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_v1_location_proto_init() }
func file_proto_v1_location_proto_init() {
	if File_proto_v1_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_location_proto_rawDesc), len(file_proto_v1_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_location_proto_goTypes,
		DependencyIndexes: file_proto_v1_location_proto_depIdxs,
		MessageInfos:      file_proto_v1_location_proto_msgTypes,
	}.Build()
	File_proto_v1_location_proto = out.File
	file_proto_v1_location_proto_goTypes = nil
	file_proto_v1_location_proto_depIdxs = nil
}
