// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/v1/chat.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RideId        string                 `protobuf:"bytes,2,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *ChatMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_proto_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ChatMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_proto_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageResponse) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type ListMessagesByRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Before        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=before,proto3" json:"before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesByRideRequest) Reset() {
	*x = ListMessagesByRideRequest{}
	mi := &file_proto_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesByRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesByRideRequest) ProtoMessage() {}

func (x *ListMessagesByRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesByRideRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesByRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ListMessagesByRideRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *ListMessagesByRideRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMessagesByRideRequest) GetBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.Before
	}
	return nil
}

type ListMessagesByRideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesByRideResponse) Reset() {
	*x = ListMessagesByRideResponse{}
	mi := &file_proto_v1_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesByRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesByRideResponse) ProtoMessage() {}

func (x *ListMessagesByRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesByRideResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesByRideResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *ListMessagesByRideResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ListMessagesBySenderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Before        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=before,proto3" json:"before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesBySenderRequest) Reset() {
	*x = ListMessagesBySenderRequest{}
	mi := &file_proto_v1_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesBySenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesBySenderRequest) ProtoMessage() {}

func (x *ListMessagesBySenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesBySenderRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesBySenderRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_chat_proto_rawDescGZIP(), []int{5}
}

func (x *ListMessagesBySenderRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ListMessagesBySenderRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMessagesBySenderRequest) GetBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.Before
	}
	return nil
}

type ListMessagesBySenderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesBySenderResponse) Reset() {
	*x = ListMessagesBySenderResponse{}
	mi := &file_proto_v1_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesBySenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesBySenderResponse) ProtoMessage() {}

func (x *ListMessagesBySenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesBySenderResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesBySenderResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ListMessagesBySenderResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ListChatsForUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Before        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=before,proto3" json:"before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsForUserRequest) Reset() {
	*x = ListChatsForUserRequest{}
	mi := &file_proto_v1_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsForUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsForUserRequest) ProtoMessage() {}

func (x *ListChatsForUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsForUserRequest.ProtoReflect.Descriptor instead.
func (*ListChatsForUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_chat_proto_rawDescGZIP(), []int{7}
}

func (x *ListChatsForUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListChatsForUserRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListChatsForUserRequest) GetBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.Before
	}
	return nil
}

type ListChatsForUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsForUserResponse) Reset() {
	*x = ListChatsForUserResponse{}
	mi := &file_proto_v1_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsForUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsForUserResponse) ProtoMessage() {}

func (x *ListChatsForUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsForUserResponse.ProtoReflect.Descriptor instead.
func (*ListChatsForUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_chat_proto_rawDescGZIP(), []int{8}
}

func (x *ListChatsForUserResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_proto_v1_chat_proto protoreflect.FileDescriptor

const file_proto_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x13proto/v1/chat.proto\x12\bproto.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa7\x01\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aride_id\x18\x02 \x01(\tR\x06rideId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"G\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"F\n" +
	"\x13SendMessageResponse\x12/\n" +
	"\amessage\x18\x01 \x01(\v2\x15.proto.v1.ChatMessageR\amessage\"~\n" +
	"\x19ListMessagesByRideRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x122\n" +
	"\x06before\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06before\"O\n" +
	"\x1aListMessagesByRideResponse\x121\n" +
	"\bmessages\x18\x01 \x03(\v2\x15.proto.v1.ChatMessageR\bmessages\"\x84\x01\n" +
	"\x1bListMessagesBySenderRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x122\n" +
	"\x06before\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06before\"Q\n" +
	"\x1cListMessagesBySenderResponse\x121\n" +
	"\bmessages\x18\x01 \x03(\v2\x15.proto.v1.ChatMessageR\bmessages\"|\n" +
	"\x17ListChatsForUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x122\n" +
	"\x06before\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06before\"M\n" +
	"\x18ListChatsForUserResponse\x121\n" +
	"\bmessages\x18\x01 \x03(\v2\x15.proto.v1.ChatMessageR\bmessages2\x84\x03\n" +
	"\vChatService\x12L\n" +
	"\vSendMessage\x12\x1c.proto.v1.SendMessageRequest\x1a\x1d.proto.v1.SendMessageResponse\"\x00\x12a\n" +
	"\x12ListMessagesByRide\x12#.proto.v1.ListMessagesByRideRequest\x1a$.proto.v1.ListMessagesByRideResponse\"\x00\x12g\n" +
	"\x14ListMessagesBySender\x12%.proto.v1.ListMessagesBySenderRequest\x1a&.proto.v1.ListMessagesBySenderResponse\"\x00\x12[\n" +
	"\x10ListChatsForUser\x12!.proto.v1.ListChatsForUserRequest\x1a\".proto.v1.ListChatsForUserResponse\"\x00B\x11Z\x0f./proto/v1/chatb\x06proto3"

var (
	file_proto_v1_chat_proto_rawDescOnce sync.Once
	file_proto_v1_chat_proto_rawDescData []byte
)

func file_proto_v1_chat_proto_rawDescGZIP() []byte {
	file_proto_v1_chat_proto_rawDescOnce.Do(func() {
		file_proto_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_chat_proto_rawDesc), len(file_proto_v1_chat_proto_rawDesc)))
	})
	return file_proto_v1_chat_proto_rawDescData
}

var file_proto_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_v1_chat_proto_goTypes = []any{
	(*ChatMessage)(nil),                  // 0: proto.v1.ChatMessage
	(*SendMessageRequest)(nil),           // 1: proto.v1.SendMessageRequest
	(*SendMessageResponse)(nil),          // 2: proto.v1.SendMessageResponse
	(*ListMessagesByRideRequest)(nil),    // 3: proto.v1.ListMessagesByRideRequest
	(*ListMessagesByRideResponse)(nil),   // 4: proto.v1.ListMessagesByRideResponse
	(*ListMessagesBySenderRequest)(nil),  // 5: proto.v1.ListMessagesBySenderRequest
	(*ListMessagesBySenderResponse)(nil), // 6: proto.v1.ListMessagesBySenderResponse
	(*ListChatsForUserRequest)(nil),      // 7: proto.v1.ListChatsForUserRequest
	(*ListChatsForUserResponse)(nil),     // 8: proto.v1.ListChatsForUserResponse
	(*timestamppb.Timestamp)(nil),        // 9: google.protobuf.Timestamp
}
var file_proto_v1_chat_proto_depIdxs = []int32{
	9,  // 0: proto.v1.ChatMessage.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: proto.v1.SendMessageResponse.message:type_name -> proto.v1.ChatMessage
	9,  // 2: proto.v1.ListMessagesByRideRequest.before:type_name -> google.protobuf.Timestamp
	0,  // 3: proto.v1.ListMessagesByRideResponse.messages:type_name -> proto.v1.ChatMessage
	9,  // 4: proto.v1.ListMessagesBySenderRequest.before:type_name -> google.protobuf.Timestamp
	0,  // 5: proto.v1.ListMessagesBySenderResponse.messages:type_name -> proto.v1.ChatMessage
	9,  // 6: proto.v1.ListChatsForUserRequest.before:type_name -> google.protobuf.Timestamp
	0,  // 7: proto.v1.ListChatsForUserResponse.messages:type_name -> proto.v1.ChatMessage
	1,  // 8: proto.v1.ChatService.SendMessage:input_type -> proto.v1.SendMessageRequest
	3,  // 9: proto.v1.ChatService.ListMessagesByRide:input_type -> proto.v1.ListMessagesByRideRequest
	5,  // 10: proto.v1.ChatService.ListMessagesBySender:input_type -> proto.v1.ListMessagesBySenderRequest
	7,  // 11: proto.v1.ChatService.ListChatsForUser:input_type -> proto.v1.ListChatsForUserRequest
	2,  // 12: proto.v1.ChatService.SendMessage:output_type -> proto.v1.SendMessageResponse
	4,  // 13: proto.v1.ChatService.ListMessagesByRide:output_type -> proto.v1.ListMessagesByRideResponse
	6,  // 14: proto.v1.ChatService.ListMessagesBySender:output_type -> proto.v1.ListMessagesBySenderResponse
	8,  // 15: proto.v1.ChatService.ListChatsForUser:output_type -> proto.v1.ListChatsForUserResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_v1_chat_proto_init() }
func file_proto_v1_chat_proto_init() {
	if File_proto_v1_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_chat_proto_rawDesc), len(file_proto_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_chat_proto_goTypes,
		DependencyIndexes: file_proto_v1_chat_proto_depIdxs,
		MessageInfos:      file_proto_v1_chat_proto_msgTypes,
	}.Build()
	File_proto_v1_chat_proto = out.File
	file_proto_v1_chat_proto_goTypes = nil
	file_proto_v1_chat_proto_depIdxs = nil
}
