// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/v1/match.proto

package match

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Match struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RiderId       string                 `protobuf:"bytes,2,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	RideId        string                 `protobuf:"bytes,4,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_proto_v1_match_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{0}
}

func (x *Match) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Match) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *Match) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Match) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *Match) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Match) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RequestToJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestToJoinRequest) Reset() {
	*x = RequestToJoinRequest{}
	mi := &file_proto_v1_match_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestToJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestToJoinRequest) ProtoMessage() {}

func (x *RequestToJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestToJoinRequest.ProtoReflect.Descriptor instead.
func (*RequestToJoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{1}
}

func (x *RequestToJoinRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

type RequestToJoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         *Match                 `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestToJoinResponse) Reset() {
	*x = RequestToJoinResponse{}
	mi := &file_proto_v1_match_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestToJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestToJoinResponse) ProtoMessage() {}

func (x *RequestToJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestToJoinResponse.ProtoReflect.Descriptor instead.
func (*RequestToJoinResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{2}
}

func (x *RequestToJoinResponse) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

type AcceptRideRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRideRequestRequest) Reset() {
	*x = AcceptRideRequestRequest{}
	mi := &file_proto_v1_match_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRideRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRideRequestRequest) ProtoMessage() {}

func (x *AcceptRideRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRideRequestRequest.ProtoReflect.Descriptor instead.
func (*AcceptRideRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptRideRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type AcceptRideRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         *Match                 `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRideRequestResponse) Reset() {
	*x = AcceptRideRequestResponse{}
	mi := &file_proto_v1_match_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRideRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRideRequestResponse) ProtoMessage() {}

func (x *AcceptRideRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRideRequestResponse.ProtoReflect.Descriptor instead.
func (*AcceptRideRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptRideRequestResponse) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

type AcceptRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRequestRequest) Reset() {
	*x = AcceptRequestRequest{}
	mi := &file_proto_v1_match_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRequestRequest) ProtoMessage() {}

func (x *AcceptRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRequestRequest.ProtoReflect.Descriptor instead.
func (*AcceptRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{5}
}

func (x *AcceptRequestRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type AcceptRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         *Match                 `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRequestResponse) Reset() {
	*x = AcceptRequestResponse{}
	mi := &file_proto_v1_match_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRequestResponse) ProtoMessage() {}

func (x *AcceptRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRequestResponse.ProtoReflect.Descriptor instead.
func (*AcceptRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{6}
}

func (x *AcceptRequestResponse) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

type RejectRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectRequestRequest) Reset() {
	*x = RejectRequestRequest{}
	mi := &file_proto_v1_match_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRequestRequest) ProtoMessage() {}

func (x *RejectRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRequestRequest.ProtoReflect.Descriptor instead.
func (*RejectRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{7}
}

func (x *RejectRequestRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type RejectRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         *Match                 `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectRequestResponse) Reset() {
	*x = RejectRequestResponse{}
	mi := &file_proto_v1_match_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRequestResponse) ProtoMessage() {}

func (x *RejectRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRequestResponse.ProtoReflect.Descriptor instead.
func (*RejectRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{8}
}

func (x *RejectRequestResponse) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

type CompleteMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMatchRequest) Reset() {
	*x = CompleteMatchRequest{}
	mi := &file_proto_v1_match_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMatchRequest) ProtoMessage() {}

func (x *CompleteMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMatchRequest.ProtoReflect.Descriptor instead.
func (*CompleteMatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{9}
}

func (x *CompleteMatchRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type CompleteMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         *Match                 `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMatchResponse) Reset() {
	*x = CompleteMatchResponse{}
	mi := &file_proto_v1_match_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMatchResponse) ProtoMessage() {}

func (x *CompleteMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMatchResponse.ProtoReflect.Descriptor instead.
func (*CompleteMatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{10}
}

func (x *CompleteMatchResponse) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

type GetMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchRequest) Reset() {
	*x = GetMatchRequest{}
	mi := &file_proto_v1_match_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchRequest) ProtoMessage() {}

func (x *GetMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchRequest.ProtoReflect.Descriptor instead.
func (*GetMatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{11}
}

func (x *GetMatchRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type GetMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         *Match                 `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchResponse) Reset() {
	*x = GetMatchResponse{}
	mi := &file_proto_v1_match_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchResponse) ProtoMessage() {}

func (x *GetMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchResponse.ProtoReflect.Descriptor instead.
func (*GetMatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{12}
}

func (x *GetMatchResponse) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

type ListMatchesByRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMatchesByRideRequest) Reset() {
	*x = ListMatchesByRideRequest{}
	mi := &file_proto_v1_match_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMatchesByRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMatchesByRideRequest) ProtoMessage() {}

func (x *ListMatchesByRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMatchesByRideRequest.ProtoReflect.Descriptor instead.
func (*ListMatchesByRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{13}
}

func (x *ListMatchesByRideRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

type ListMatchesByRideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*Match               `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMatchesByRideResponse) Reset() {
	*x = ListMatchesByRideResponse{}
	mi := &file_proto_v1_match_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMatchesByRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMatchesByRideResponse) ProtoMessage() {}

func (x *ListMatchesByRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMatchesByRideResponse.ProtoReflect.Descriptor instead.
func (*ListMatchesByRideResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{14}
}

func (x *ListMatchesByRideResponse) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

type ListMatchesByRiderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiderId       string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMatchesByRiderRequest) Reset() {
	*x = ListMatchesByRiderRequest{}
	mi := &file_proto_v1_match_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMatchesByRiderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMatchesByRiderRequest) ProtoMessage() {}

func (x *ListMatchesByRiderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMatchesByRiderRequest.ProtoReflect.Descriptor instead.
func (*ListMatchesByRiderRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{15}
}

func (x *ListMatchesByRiderRequest) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

type ListMatchesByRiderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*Match               `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMatchesByRiderResponse) Reset() {
	*x = ListMatchesByRiderResponse{}
	mi := &file_proto_v1_match_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMatchesByRiderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMatchesByRiderResponse) ProtoMessage() {}

func (x *ListMatchesByRiderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMatchesByRiderResponse.ProtoReflect.Descriptor instead.
func (*ListMatchesByRiderResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{16}
}

func (x *ListMatchesByRiderResponse) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

type ListMyMatchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyMatchesRequest) Reset() {
	*x = ListMyMatchesRequest{}
	mi := &file_proto_v1_match_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyMatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyMatchesRequest) ProtoMessage() {}

func (x *ListMyMatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyMatchesRequest.ProtoReflect.Descriptor instead.
func (*ListMyMatchesRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{17}
}

type ListMyMatchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*Match               `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyMatchesResponse) Reset() {
	*x = ListMyMatchesResponse{}
	mi := &file_proto_v1_match_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyMatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyMatchesResponse) ProtoMessage() {}

func (x *ListMyMatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyMatchesResponse.ProtoReflect.Descriptor instead.
func (*ListMyMatchesResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{18}
}

func (x *ListMyMatchesResponse) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

var File_proto_v1_match_proto protoreflect.FileDescriptor

const file_proto_v1_match_proto_rawDesc = "" +
	"\n" +
	"\x14proto/v1/match.proto\x12\bproto.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x01\n" +
	"\x05Match\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\brider_id\x18\x02 \x01(\tR\ariderId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12\x17\n" +
	"\aride_id\x18\x04 \x01(\tR\x06rideId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"/\n" +
	"\x14RequestToJoinRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\">\n" +
	"\x15RequestToJoinResponse\x12%\n" +
	"\x05match\x18\x01 \x01(\v2\x0f.proto.v1.MatchR\x05match\"9\n" +
	"\x18AcceptRideRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"B\n" +
	"\x19AcceptRideRequestResponse\x12%\n" +
	"\x05match\x18\x01 \x01(\v2\x0f.proto.v1.MatchR\x05match\"1\n" +
	"\x14AcceptRequestRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\">\n" +
	"\x15AcceptRequestResponse\x12%\n" +
	"\x05match\x18\x01 \x01(\v2\x0f.proto.v1.MatchR\x05match\"1\n" +
	"\x14RejectRequestRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\">\n" +
	"\x15RejectRequestResponse\x12%\n" +
	"\x05match\x18\x01 \x01(\v2\x0f.proto.v1.MatchR\x05match\"1\n" +
	"\x14CompleteMatchRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\">\n" +
	"\x15CompleteMatchResponse\x12%\n" +
	"\x05match\x18\x01 \x01(\v2\x0f.proto.v1.MatchR\x05match\",\n" +
	"\x0fGetMatchRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\"9\n" +
	"\x10GetMatchResponse\x12%\n" +
	"\x05match\x18\x01 \x01(\v2\x0f.proto.v1.MatchR\x05match\"3\n" +
	"\x18ListMatchesByRideRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\"F\n" +
	"\x19ListMatchesByRideResponse\x12)\n" +
	"\amatches\x18\x01 \x03(\v2\x0f.proto.v1.MatchR\amatches\"6\n" +
	"\x19ListMatchesByRiderRequest\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\"G\n" +
	"\x1aListMatchesByRiderResponse\x12)\n" +
	"\amatches\x18\x01 \x03(\v2\x0f.proto.v1.MatchR\amatches\"\x16\n" +
	"\x14ListMyMatchesRequest\"B\n" +
	"\x15ListMyMatchesResponse\x12)\n" +
	"\amatches\x18\x01 \x03(\v2\x0f.proto.v1.MatchR\amatches2\x88\x06\n" +
	"\fMatchService\x12P\n" +
	"\rRequestToJoin\x12\x1e.proto.v1.RequestToJoinRequest\x1a\x1f.proto.v1.RequestToJoinResponse\x12\\\n" +
	"\x11AcceptRideRequest\x12\".proto.v1.AcceptRideRequestRequest\x1a#.proto.v1.AcceptRideRequestResponse\x12P\n" +
	"\rAcceptRequest\x12\x1e.proto.v1.AcceptRequestRequest\x1a\x1f.proto.v1.AcceptRequestResponse\x12P\n" +
	"\rRejectRequest\x12\x1e.proto.v1.RejectRequestRequest\x1a\x1f.proto.v1.RejectRequestResponse\x12P\n" +
	"\rCompleteMatch\x12\x1e.proto.v1.CompleteMatchRequest\x1a\x1f.proto.v1.CompleteMatchResponse\x12A\n" +
	"\bGetMatch\x12\x19.proto.v1.GetMatchRequest\x1a\x1a.proto.v1.GetMatchResponse\x12\\\n" +
	"\x11ListMatchesByRide\x12\".proto.v1.ListMatchesByRideRequest\x1a#.proto.v1.ListMatchesByRideResponse\x12_\n" +
	"\x12ListMatchesByRider\x12#.proto.v1.ListMatchesByRiderRequest\x1a$.proto.v1.ListMatchesByRiderResponse\x12P\n" +
	"\rListMyMatches\x12\x1e.proto.v1.ListMyMatchesRequest\x1a\x1f.proto.v1.ListMyMatchesResponseB\x12Z\x10./proto/v1/matchb\x06proto3"

var (
	file_proto_v1_match_proto_rawDescOnce sync.Once
	file_proto_v1_match_proto_rawDescData []byte
)

func file_proto_v1_match_proto_rawDescGZIP() []byte {
	file_proto_v1_match_proto_rawDescOnce.Do(func() {
		file_proto_v1_match_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_match_proto_rawDesc), len(file_proto_v1_match_proto_rawDesc)))
	})
	return file_proto_v1_match_proto_rawDescData
}

var file_proto_v1_match_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_v1_match_proto_goTypes = []any{
	(*Match)(nil),                      // 0: proto.v1.Match
	(*RequestToJoinRequest)(nil),       // 1: proto.v1.RequestToJoinRequest
	(*RequestToJoinResponse)(nil),      // 2: proto.v1.RequestToJoinResponse
	(*AcceptRideRequestRequest)(nil),   // 3: proto.v1.AcceptRideRequestRequest
	(*AcceptRideRequestResponse)(nil),  // 4: proto.v1.AcceptRideRequestResponse
	(*AcceptRequestRequest)(nil),       // 5: proto.v1.AcceptRequestRequest
	(*AcceptRequestResponse)(nil),      // 6: proto.v1.AcceptRequestResponse
	(*RejectRequestRequest)(nil),       // 7: proto.v1.RejectRequestRequest
	(*RejectRequestResponse)(nil),      // 8: proto.v1.RejectRequestResponse
	(*CompleteMatchRequest)(nil),       // 9: proto.v1.CompleteMatchRequest
	(*CompleteMatchResponse)(nil),      // 10: proto.v1.CompleteMatchResponse
	(*GetMatchRequest)(nil),            // 11: proto.v1.GetMatchRequest
	(*GetMatchResponse)(nil),           // 12: proto.v1.GetMatchResponse
	(*ListMatchesByRideRequest)(nil),   // 13: proto.v1.ListMatchesByRideRequest
	(*ListMatchesByRideResponse)(nil),  // 14: proto.v1.ListMatchesByRideResponse
	(*ListMatchesByRiderRequest)(nil),  // 15: proto.v1.ListMatchesByRiderRequest
	(*ListMatchesByRiderResponse)(nil), // 16: proto.v1.ListMatchesByRiderResponse
	(*ListMyMatchesRequest)(nil),       // 17: proto.v1.ListMyMatchesRequest
	(*ListMyMatchesResponse)(nil),      // 18: proto.v1.ListMyMatchesResponse
	(*timestamppb.Timestamp)(nil),      // 19: google.protobuf.Timestamp
}
var file_proto_v1_match_proto_depIdxs = []int32{
	19, // 0: proto.v1.Match.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: proto.v1.RequestToJoinResponse.match:type_name -> proto.v1.Match
	0,  // 2: proto.v1.AcceptRideRequestResponse.match:type_name -> proto.v1.Match
	0,  // 3: proto.v1.AcceptRequestResponse.match:type_name -> proto.v1.Match
	0,  // 4: proto.v1.RejectRequestResponse.match:type_name -> proto.v1.Match
	0,  // 5: proto.v1.CompleteMatchResponse.match:type_name -> proto.v1.Match
	0,  // 6: proto.v1.GetMatchResponse.match:type_name -> proto.v1.Match
	0,  // 7: proto.v1.ListMatchesByRideResponse.matches:type_name -> proto.v1.Match
	0,  // 8: proto.v1.ListMatchesByRiderResponse.matches:type_name -> proto.v1.Match
	0,  // 9: proto.v1.ListMyMatchesResponse.matches:type_name -> proto.v1.Match
	1,  // 10: proto.v1.MatchService.RequestToJoin:input_type -> proto.v1.RequestToJoinRequest
	3,  // 11: proto.v1.MatchService.AcceptRideRequest:input_type -> proto.v1.AcceptRideRequestRequest
	5,  // 12: proto.v1.MatchService.AcceptRequest:input_type -> proto.v1.AcceptRequestRequest
	7,  // 13: proto.v1.MatchService.RejectRequest:input_type -> proto.v1.RejectRequestRequest
	9,  // 14: proto.v1.MatchService.CompleteMatch:input_type -> proto.v1.CompleteMatchRequest
	11, // 15: proto.v1.MatchService.GetMatch:input_type -> proto.v1.GetMatchRequest
	13, // 16: proto.v1.MatchService.ListMatchesByRide:input_type -> proto.v1.ListMatchesByRideRequest
	15, // 17: proto.v1.MatchService.ListMatchesByRider:input_type -> proto.v1.ListMatchesByRiderRequest
	17, // 18: proto.v1.MatchService.ListMyMatches:input_type -> proto.v1.ListMyMatchesRequest
	2,  // 19: proto.v1.MatchService.RequestToJoin:output_type -> proto.v1.RequestToJoinResponse
	4,  // 20: proto.v1.MatchService.AcceptRideRequest:output_type -> proto.v1.AcceptRideRequestResponse
	6,  // 21: proto.v1.MatchService.AcceptRequest:output_type -> proto.v1.AcceptRequestResponse
	8,  // 22: proto.v1.MatchService.RejectRequest:output_type -> proto.v1.RejectRequestResponse
	10, // 23: proto.v1.MatchService.CompleteMatch:output_type -> proto.v1.CompleteMatchResponse
	12, // 24: proto.v1.MatchService.GetMatch:output_type -> proto.v1.GetMatchResponse
	14, // 25: proto.v1.MatchService.ListMatchesByRide:output_type -> proto.v1.ListMatchesByRideResponse
	16, // 26: proto.v1.MatchService.ListMatchesByRider:output_type -> proto.v1.ListMatchesByRiderResponse
	18, // 27: proto.v1.MatchService.ListMyMatches:output_type -> proto.v1.ListMyMatchesResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_v1_match_proto_init() }
func file_proto_v1_match_proto_init() {
	if File_proto_v1_match_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_match_proto_rawDesc), len(file_proto_v1_match_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_match_proto_goTypes,
		DependencyIndexes: file_proto_v1_match_proto_depIdxs,
		MessageInfos:      file_proto_v1_match_proto_msgTypes,
	}.Build()
	File_proto_v1_match_proto = out.File
	file_proto_v1_match_proto_goTypes = nil
	file_proto_v1_match_proto_depIdxs = nil
}
