// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/v1/match.proto

package match

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Match struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RiderId       string                 `protobuf:"bytes,2,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	RideId        string                 `protobuf:"bytes,4,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                        // "requested", "accepted", "rejected", "completed"
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Match create hone ka time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_proto_v1_match_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{0}
}

func (x *Match) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Match) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *Match) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Match) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *Match) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Match) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Rider jab ek ride join karna chahta hai, to ye request bhejta hai
type RequestToJoinRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rider_id, driver_id, ride_id client se aayega; status aur created_at server set karega
	Match         *Match `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestToJoinRequest) Reset() {
	*x = RequestToJoinRequest{}
	mi := &file_proto_v1_match_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestToJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestToJoinRequest) ProtoMessage() {}

func (x *RequestToJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestToJoinRequest.ProtoReflect.Descriptor instead.
func (*RequestToJoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{1}
}

func (x *RequestToJoinRequest) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

type RequestToJoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         *Match                 `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"` // Server se status="requested" ke sath match return hoga
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestToJoinResponse) Reset() {
	*x = RequestToJoinResponse{}
	mi := &file_proto_v1_match_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestToJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestToJoinResponse) ProtoMessage() {}

func (x *RequestToJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestToJoinResponse.ProtoReflect.Descriptor instead.
func (*RequestToJoinResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{2}
}

func (x *RequestToJoinResponse) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

// Request accept karne ka request
type AcceptRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRequestRequest) Reset() {
	*x = AcceptRequestRequest{}
	mi := &file_proto_v1_match_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRequestRequest) ProtoMessage() {}

func (x *AcceptRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRequestRequest.ProtoReflect.Descriptor instead.
func (*AcceptRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptRequestRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type AcceptRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         *Match                 `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"` // Status ab "accepted" ho jayega
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRequestResponse) Reset() {
	*x = AcceptRequestResponse{}
	mi := &file_proto_v1_match_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRequestResponse) ProtoMessage() {}

func (x *AcceptRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRequestResponse.ProtoReflect.Descriptor instead.
func (*AcceptRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptRequestResponse) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

// Request reject karne ka request
type RejectRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectRequestRequest) Reset() {
	*x = RejectRequestRequest{}
	mi := &file_proto_v1_match_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRequestRequest) ProtoMessage() {}

func (x *RejectRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRequestRequest.ProtoReflect.Descriptor instead.
func (*RejectRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{5}
}

func (x *RejectRequestRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type RejectRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         *Match                 `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"` // Status ab "rejected" ho jayega
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectRequestResponse) Reset() {
	*x = RejectRequestResponse{}
	mi := &file_proto_v1_match_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRequestResponse) ProtoMessage() {}

func (x *RejectRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRequestResponse.ProtoReflect.Descriptor instead.
func (*RejectRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{6}
}

func (x *RejectRequestResponse) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

// Ride complete hone ke baad match ko complete mark karne ka request
type CompleteMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMatchRequest) Reset() {
	*x = CompleteMatchRequest{}
	mi := &file_proto_v1_match_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMatchRequest) ProtoMessage() {}

func (x *CompleteMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMatchRequest.ProtoReflect.Descriptor instead.
func (*CompleteMatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{7}
}

func (x *CompleteMatchRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type CompleteMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         *Match                 `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"` // Status ab "completed" ho jayega
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMatchResponse) Reset() {
	*x = CompleteMatchResponse{}
	mi := &file_proto_v1_match_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMatchResponse) ProtoMessage() {}

func (x *CompleteMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMatchResponse.ProtoReflect.Descriptor instead.
func (*CompleteMatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{8}
}

func (x *CompleteMatchResponse) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

// Match details nikalne ka request
type GetMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchRequest) Reset() {
	*x = GetMatchRequest{}
	mi := &file_proto_v1_match_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchRequest) ProtoMessage() {}

func (x *GetMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchRequest.ProtoReflect.Descriptor instead.
func (*GetMatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{9}
}

func (x *GetMatchRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type GetMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         *Match                 `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchResponse) Reset() {
	*x = GetMatchResponse{}
	mi := &file_proto_v1_match_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchResponse) ProtoMessage() {}

func (x *GetMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchResponse.ProtoReflect.Descriptor instead.
func (*GetMatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{10}
}

func (x *GetMatchResponse) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

// Ek specific ride ke saare matches ka request
type ListMatchesByRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMatchesByRideRequest) Reset() {
	*x = ListMatchesByRideRequest{}
	mi := &file_proto_v1_match_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMatchesByRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMatchesByRideRequest) ProtoMessage() {}

func (x *ListMatchesByRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMatchesByRideRequest.ProtoReflect.Descriptor instead.
func (*ListMatchesByRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{11}
}

func (x *ListMatchesByRideRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

type ListMatchesByRideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*Match               `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"` // Saare matches ka list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMatchesByRideResponse) Reset() {
	*x = ListMatchesByRideResponse{}
	mi := &file_proto_v1_match_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMatchesByRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMatchesByRideResponse) ProtoMessage() {}

func (x *ListMatchesByRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMatchesByRideResponse.ProtoReflect.Descriptor instead.
func (*ListMatchesByRideResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{12}
}

func (x *ListMatchesByRideResponse) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

// Ek rider ke initiate kiye huye saare matches ka request
type ListMatchesByRiderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiderId       string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMatchesByRiderRequest) Reset() {
	*x = ListMatchesByRiderRequest{}
	mi := &file_proto_v1_match_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMatchesByRiderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMatchesByRiderRequest) ProtoMessage() {}

func (x *ListMatchesByRiderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMatchesByRiderRequest.ProtoReflect.Descriptor instead.
func (*ListMatchesByRiderRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{13}
}

func (x *ListMatchesByRiderRequest) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

type ListMatchesByRiderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*Match               `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"` // Saare matches ka list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMatchesByRiderResponse) Reset() {
	*x = ListMatchesByRiderResponse{}
	mi := &file_proto_v1_match_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMatchesByRiderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMatchesByRiderResponse) ProtoMessage() {}

func (x *ListMatchesByRiderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_match_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMatchesByRiderResponse.ProtoReflect.Descriptor instead.
func (*ListMatchesByRiderResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_match_proto_rawDescGZIP(), []int{14}
}

func (x *ListMatchesByRiderResponse) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

var File_proto_v1_match_proto protoreflect.FileDescriptor

const file_proto_v1_match_proto_rawDesc = "" +
	"\n" +
	"\x14proto/v1/match.proto\x12\bproto.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x01\n" +
	"\x05Match\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\brider_id\x18\x02 \x01(\tR\ariderId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12\x17\n" +
	"\aride_id\x18\x04 \x01(\tR\x06rideId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"=\n" +
	"\x14RequestToJoinRequest\x12%\n" +
	"\x05match\x18\x01 \x01(\v2\x0f.proto.v1.MatchR\x05match\">\n" +
	"\x15RequestToJoinResponse\x12%\n" +
	"\x05match\x18\x01 \x01(\v2\x0f.proto.v1.MatchR\x05match\"1\n" +
	"\x14AcceptRequestRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\">\n" +
	"\x15AcceptRequestResponse\x12%\n" +
	"\x05match\x18\x01 \x01(\v2\x0f.proto.v1.MatchR\x05match\"1\n" +
	"\x14RejectRequestRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\">\n" +
	"\x15RejectRequestResponse\x12%\n" +
	"\x05match\x18\x01 \x01(\v2\x0f.proto.v1.MatchR\x05match\"1\n" +
	"\x14CompleteMatchRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\">\n" +
	"\x15CompleteMatchResponse\x12%\n" +
	"\x05match\x18\x01 \x01(\v2\x0f.proto.v1.MatchR\x05match\",\n" +
	"\x0fGetMatchRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\"9\n" +
	"\x10GetMatchResponse\x12%\n" +
	"\x05match\x18\x01 \x01(\v2\x0f.proto.v1.MatchR\x05match\"3\n" +
	"\x18ListMatchesByRideRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\"F\n" +
	"\x19ListMatchesByRideResponse\x12)\n" +
	"\amatches\x18\x01 \x03(\v2\x0f.proto.v1.MatchR\amatches\"6\n" +
	"\x19ListMatchesByRiderRequest\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\"G\n" +
	"\x1aListMatchesByRiderResponse\x12)\n" +
	"\amatches\x18\x01 \x03(\v2\x0f.proto.v1.MatchR\amatches2\xe6\x04\n" +
	"\fMatchService\x12R\n" +
	"\rRequestToJoin\x12\x1e.proto.v1.RequestToJoinRequest\x1a\x1f.proto.v1.RequestToJoinResponse\"\x00\x12R\n" +
	"\rAcceptRequest\x12\x1e.proto.v1.AcceptRequestRequest\x1a\x1f.proto.v1.AcceptRequestResponse\"\x00\x12R\n" +
	"\rRejectRequest\x12\x1e.proto.v1.RejectRequestRequest\x1a\x1f.proto.v1.RejectRequestResponse\"\x00\x12R\n" +
	"\rCompleteMatch\x12\x1e.proto.v1.CompleteMatchRequest\x1a\x1f.proto.v1.CompleteMatchResponse\"\x00\x12C\n" +
	"\bGetMatch\x12\x19.proto.v1.GetMatchRequest\x1a\x1a.proto.v1.GetMatchResponse\"\x00\x12^\n" +
	"\x11ListMatchesByRide\x12\".proto.v1.ListMatchesByRideRequest\x1a#.proto.v1.ListMatchesByRideResponse\"\x00\x12a\n" +
	"\x12ListMatchesByRider\x12#.proto.v1.ListMatchesByRiderRequest\x1a$.proto.v1.ListMatchesByRiderResponse\"\x00B\x12Z\x10./proto/v1/matchb\x06proto3"

var (
	file_proto_v1_match_proto_rawDescOnce sync.Once
	file_proto_v1_match_proto_rawDescData []byte
)

func file_proto_v1_match_proto_rawDescGZIP() []byte {
	file_proto_v1_match_proto_rawDescOnce.Do(func() {
		file_proto_v1_match_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_match_proto_rawDesc), len(file_proto_v1_match_proto_rawDesc)))
	})
	return file_proto_v1_match_proto_rawDescData
}

var file_proto_v1_match_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_v1_match_proto_goTypes = []any{
	(*Match)(nil),                      // 0: proto.v1.Match
	(*RequestToJoinRequest)(nil),       // 1: proto.v1.RequestToJoinRequest
	(*RequestToJoinResponse)(nil),      // 2: proto.v1.RequestToJoinResponse
	(*AcceptRequestRequest)(nil),       // 3: proto.v1.AcceptRequestRequest
	(*AcceptRequestResponse)(nil),      // 4: proto.v1.AcceptRequestResponse
	(*RejectRequestRequest)(nil),       // 5: proto.v1.RejectRequestRequest
	(*RejectRequestResponse)(nil),      // 6: proto.v1.RejectRequestResponse
	(*CompleteMatchRequest)(nil),       // 7: proto.v1.CompleteMatchRequest
	(*CompleteMatchResponse)(nil),      // 8: proto.v1.CompleteMatchResponse
	(*GetMatchRequest)(nil),            // 9: proto.v1.GetMatchRequest
	(*GetMatchResponse)(nil),           // 10: proto.v1.GetMatchResponse
	(*ListMatchesByRideRequest)(nil),   // 11: proto.v1.ListMatchesByRideRequest
	(*ListMatchesByRideResponse)(nil),  // 12: proto.v1.ListMatchesByRideResponse
	(*ListMatchesByRiderRequest)(nil),  // 13: proto.v1.ListMatchesByRiderRequest
	(*ListMatchesByRiderResponse)(nil), // 14: proto.v1.ListMatchesByRiderResponse
	(*timestamppb.Timestamp)(nil),      // 15: google.protobuf.Timestamp
}
var file_proto_v1_match_proto_depIdxs = []int32{
	15, // 0: proto.v1.Match.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: proto.v1.RequestToJoinRequest.match:type_name -> proto.v1.Match
	0,  // 2: proto.v1.RequestToJoinResponse.match:type_name -> proto.v1.Match
	0,  // 3: proto.v1.AcceptRequestResponse.match:type_name -> proto.v1.Match
	0,  // 4: proto.v1.RejectRequestResponse.match:type_name -> proto.v1.Match
	0,  // 5: proto.v1.CompleteMatchResponse.match:type_name -> proto.v1.Match
	0,  // 6: proto.v1.GetMatchResponse.match:type_name -> proto.v1.Match
	0,  // 7: proto.v1.ListMatchesByRideResponse.matches:type_name -> proto.v1.Match
	0,  // 8: proto.v1.ListMatchesByRiderResponse.matches:type_name -> proto.v1.Match
	1,  // 9: proto.v1.MatchService.RequestToJoin:input_type -> proto.v1.RequestToJoinRequest
	3,  // 10: proto.v1.MatchService.AcceptRequest:input_type -> proto.v1.AcceptRequestRequest
	5,  // 11: proto.v1.MatchService.RejectRequest:input_type -> proto.v1.RejectRequestRequest
	7,  // 12: proto.v1.MatchService.CompleteMatch:input_type -> proto.v1.CompleteMatchRequest
	9,  // 13: proto.v1.MatchService.GetMatch:input_type -> proto.v1.GetMatchRequest
	11, // 14: proto.v1.MatchService.ListMatchesByRide:input_type -> proto.v1.ListMatchesByRideRequest
	13, // 15: proto.v1.MatchService.ListMatchesByRider:input_type -> proto.v1.ListMatchesByRiderRequest
	2,  // 16: proto.v1.MatchService.RequestToJoin:output_type -> proto.v1.RequestToJoinResponse
	4,  // 17: proto.v1.MatchService.AcceptRequest:output_type -> proto.v1.AcceptRequestResponse
	6,  // 18: proto.v1.MatchService.RejectRequest:output_type -> proto.v1.RejectRequestResponse
	8,  // 19: proto.v1.MatchService.CompleteMatch:output_type -> proto.v1.CompleteMatchResponse
	10, // 20: proto.v1.MatchService.GetMatch:output_type -> proto.v1.GetMatchResponse
	12, // 21: proto.v1.MatchService.ListMatchesByRide:output_type -> proto.v1.ListMatchesByRideResponse
	14, // 22: proto.v1.MatchService.ListMatchesByRider:output_type -> proto.v1.ListMatchesByRiderResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_v1_match_proto_init() }
func file_proto_v1_match_proto_init() {
	if File_proto_v1_match_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_match_proto_rawDesc), len(file_proto_v1_match_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_match_proto_goTypes,
		DependencyIndexes: file_proto_v1_match_proto_depIdxs,
		MessageInfos:      file_proto_v1_match_proto_msgTypes,
	}.Build()
	File_proto_v1_match_proto = out.File
	file_proto_v1_match_proto_goTypes = nil
	file_proto_v1_match_proto_depIdxs = nil
}
