// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/v1/ride.proto

package ride

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RideOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	FromGeo       string                 `protobuf:"bytes,3,opt,name=from_geo,json=fromGeo,proto3" json:"from_geo,omitempty"`
	ToGeo         string                 `protobuf:"bytes,4,opt,name=to_geo,json=toGeo,proto3" json:"to_geo,omitempty"`
	Fare          float64                `protobuf:"fixed64,5,opt,name=fare,proto3" json:"fare,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`
	Seats         int32                  `protobuf:"varint,7,opt,name=seats,proto3" json:"seats,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RideOffer) Reset() {
	*x = RideOffer{}
	mi := &file_proto_v1_ride_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RideOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideOffer) ProtoMessage() {}

func (x *RideOffer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideOffer.ProtoReflect.Descriptor instead.
func (*RideOffer) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{0}
}

func (x *RideOffer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RideOffer) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *RideOffer) GetFromGeo() string {
	if x != nil {
		return x.FromGeo
	}
	return ""
}

func (x *RideOffer) GetToGeo() string {
	if x != nil {
		return x.ToGeo
	}
	return ""
}

func (x *RideOffer) GetFare() float64 {
	if x != nil {
		return x.Fare
	}
	return 0
}

func (x *RideOffer) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *RideOffer) GetSeats() int32 {
	if x != nil {
		return x.Seats
	}
	return 0
}

func (x *RideOffer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FromGeo       string                 `protobuf:"bytes,3,opt,name=from_geo,json=fromGeo,proto3" json:"from_geo,omitempty"`
	ToGeo         string                 `protobuf:"bytes,4,opt,name=to_geo,json=toGeo,proto3" json:"to_geo,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	Seats         int32                  `protobuf:"varint,6,opt,name=seats,proto3" json:"seats,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RideRequest) Reset() {
	*x = RideRequest{}
	mi := &file_proto_v1_ride_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideRequest) ProtoMessage() {}

func (x *RideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideRequest.ProtoReflect.Descriptor instead.
func (*RideRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{1}
}

func (x *RideRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RideRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RideRequest) GetFromGeo() string {
	if x != nil {
		return x.FromGeo
	}
	return ""
}

func (x *RideRequest) GetToGeo() string {
	if x != nil {
		return x.ToGeo
	}
	return ""
}

func (x *RideRequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *RideRequest) GetSeats() int32 {
	if x != nil {
		return x.Seats
	}
	return 0
}

func (x *RideRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateOfferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromGeo       string                 `protobuf:"bytes,1,opt,name=from_geo,json=fromGeo,proto3" json:"from_geo,omitempty"`
	ToGeo         string                 `protobuf:"bytes,2,opt,name=to_geo,json=toGeo,proto3" json:"to_geo,omitempty"`
	Fare          float64                `protobuf:"fixed64,3,opt,name=fare,proto3" json:"fare,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	Seats         int32                  `protobuf:"varint,5,opt,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOfferRequest) Reset() {
	*x = CreateOfferRequest{}
	mi := &file_proto_v1_ride_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOfferRequest) ProtoMessage() {}

func (x *CreateOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOfferRequest.ProtoReflect.Descriptor instead.
func (*CreateOfferRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOfferRequest) GetFromGeo() string {
	if x != nil {
		return x.FromGeo
	}
	return ""
}

func (x *CreateOfferRequest) GetToGeo() string {
	if x != nil {
		return x.ToGeo
	}
	return ""
}

func (x *CreateOfferRequest) GetFare() float64 {
	if x != nil {
		return x.Fare
	}
	return 0
}

func (x *CreateOfferRequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *CreateOfferRequest) GetSeats() int32 {
	if x != nil {
		return x.Seats
	}
	return 0
}

type CreateOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offer         *RideOffer             `protobuf:"bytes,1,opt,name=offer,proto3" json:"offer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOfferResponse) Reset() {
	*x = CreateOfferResponse{}
	mi := &file_proto_v1_ride_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOfferResponse) ProtoMessage() {}

func (x *CreateOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOfferResponse.ProtoReflect.Descriptor instead.
func (*CreateOfferResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOfferResponse) GetOffer() *RideOffer {
	if x != nil {
		return x.Offer
	}
	return nil
}

type GetOfferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOfferRequest) Reset() {
	*x = GetOfferRequest{}
	mi := &file_proto_v1_ride_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfferRequest) ProtoMessage() {}

func (x *GetOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfferRequest.ProtoReflect.Descriptor instead.
func (*GetOfferRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{4}
}

func (x *GetOfferRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offer         *RideOffer             `protobuf:"bytes,1,opt,name=offer,proto3" json:"offer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOfferResponse) Reset() {
	*x = GetOfferResponse{}
	mi := &file_proto_v1_ride_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfferResponse) ProtoMessage() {}

func (x *GetOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfferResponse.ProtoReflect.Descriptor instead.
func (*GetOfferResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{5}
}

func (x *GetOfferResponse) GetOffer() *RideOffer {
	if x != nil {
		return x.Offer
	}
	return nil
}

type UpdateOfferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fare          float64                `protobuf:"fixed64,2,opt,name=fare,proto3" json:"fare,omitempty"`
	Seats         int32                  `protobuf:"varint,3,opt,name=seats,proto3" json:"seats,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOfferRequest) Reset() {
	*x = UpdateOfferRequest{}
	mi := &file_proto_v1_ride_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOfferRequest) ProtoMessage() {}

func (x *UpdateOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOfferRequest.ProtoReflect.Descriptor instead.
func (*UpdateOfferRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateOfferRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOfferRequest) GetFare() float64 {
	if x != nil {
		return x.Fare
	}
	return 0
}

func (x *UpdateOfferRequest) GetSeats() int32 {
	if x != nil {
		return x.Seats
	}
	return 0
}

func (x *UpdateOfferRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offer         *RideOffer             `protobuf:"bytes,1,opt,name=offer,proto3" json:"offer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOfferResponse) Reset() {
	*x = UpdateOfferResponse{}
	mi := &file_proto_v1_ride_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOfferResponse) ProtoMessage() {}

func (x *UpdateOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOfferResponse.ProtoReflect.Descriptor instead.
func (*UpdateOfferResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateOfferResponse) GetOffer() *RideOffer {
	if x != nil {
		return x.Offer
	}
	return nil
}

type DeleteOfferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOfferRequest) Reset() {
	*x = DeleteOfferRequest{}
	mi := &file_proto_v1_ride_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOfferRequest) ProtoMessage() {}

func (x *DeleteOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOfferRequest.ProtoReflect.Descriptor instead.
func (*DeleteOfferRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteOfferRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOfferResponse) Reset() {
	*x = DeleteOfferResponse{}
	mi := &file_proto_v1_ride_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOfferResponse) ProtoMessage() {}

func (x *DeleteOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOfferResponse.ProtoReflect.Descriptor instead.
func (*DeleteOfferResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteOfferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListNearbyOffersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GeohashPrefix string                 `protobuf:"bytes,1,opt,name=geohash_prefix,json=geohashPrefix,proto3" json:"geohash_prefix,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNearbyOffersRequest) Reset() {
	*x = ListNearbyOffersRequest{}
	mi := &file_proto_v1_ride_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNearbyOffersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNearbyOffersRequest) ProtoMessage() {}

func (x *ListNearbyOffersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNearbyOffersRequest.ProtoReflect.Descriptor instead.
func (*ListNearbyOffersRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{10}
}

func (x *ListNearbyOffersRequest) GetGeohashPrefix() string {
	if x != nil {
		return x.GeohashPrefix
	}
	return ""
}

func (x *ListNearbyOffersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListNearbyOffersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offers        []*RideOffer           `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNearbyOffersResponse) Reset() {
	*x = ListNearbyOffersResponse{}
	mi := &file_proto_v1_ride_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNearbyOffersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNearbyOffersResponse) ProtoMessage() {}

func (x *ListNearbyOffersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNearbyOffersResponse.ProtoReflect.Descriptor instead.
func (*ListNearbyOffersResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{11}
}

func (x *ListNearbyOffersResponse) GetOffers() []*RideOffer {
	if x != nil {
		return x.Offers
	}
	return nil
}

type ListMyOffersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyOffersRequest) Reset() {
	*x = ListMyOffersRequest{}
	mi := &file_proto_v1_ride_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyOffersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyOffersRequest) ProtoMessage() {}

func (x *ListMyOffersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyOffersRequest.ProtoReflect.Descriptor instead.
func (*ListMyOffersRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{12}
}

func (x *ListMyOffersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMyOffersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offers        []*RideOffer           `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyOffersResponse) Reset() {
	*x = ListMyOffersResponse{}
	mi := &file_proto_v1_ride_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyOffersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyOffersResponse) ProtoMessage() {}

func (x *ListMyOffersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyOffersResponse.ProtoReflect.Descriptor instead.
func (*ListMyOffersResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{13}
}

func (x *ListMyOffersResponse) GetOffers() []*RideOffer {
	if x != nil {
		return x.Offers
	}
	return nil
}

type CreateRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromGeo       string                 `protobuf:"bytes,1,opt,name=from_geo,json=fromGeo,proto3" json:"from_geo,omitempty"`
	ToGeo         string                 `protobuf:"bytes,2,opt,name=to_geo,json=toGeo,proto3" json:"to_geo,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Seats         int32                  `protobuf:"varint,4,opt,name=seats,proto3" json:"seats,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequestRequest) Reset() {
	*x = CreateRequestRequest{}
	mi := &file_proto_v1_ride_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequestRequest) ProtoMessage() {}

func (x *CreateRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequestRequest.ProtoReflect.Descriptor instead.
func (*CreateRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{14}
}

func (x *CreateRequestRequest) GetFromGeo() string {
	if x != nil {
		return x.FromGeo
	}
	return ""
}

func (x *CreateRequestRequest) GetToGeo() string {
	if x != nil {
		return x.ToGeo
	}
	return ""
}

func (x *CreateRequestRequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *CreateRequestRequest) GetSeats() int32 {
	if x != nil {
		return x.Seats
	}
	return 0
}

func (x *CreateRequestRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *RideRequest           `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequestResponse) Reset() {
	*x = CreateRequestResponse{}
	mi := &file_proto_v1_ride_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequestResponse) ProtoMessage() {}

func (x *CreateRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequestResponse.ProtoReflect.Descriptor instead.
func (*CreateRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{15}
}

func (x *CreateRequestResponse) GetRequest() *RideRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type GetRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequestRequest) Reset() {
	*x = GetRequestRequest{}
	mi := &file_proto_v1_ride_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestRequest) ProtoMessage() {}

func (x *GetRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestRequest.ProtoReflect.Descriptor instead.
func (*GetRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{16}
}

func (x *GetRequestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *RideRequest           `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequestResponse) Reset() {
	*x = GetRequestResponse{}
	mi := &file_proto_v1_ride_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestResponse) ProtoMessage() {}

func (x *GetRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestResponse.ProtoReflect.Descriptor instead.
func (*GetRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{17}
}

func (x *GetRequestResponse) GetRequest() *RideRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type UpdateRequestStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequestStatusRequest) Reset() {
	*x = UpdateRequestStatusRequest{}
	mi := &file_proto_v1_ride_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequestStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequestStatusRequest) ProtoMessage() {}

func (x *UpdateRequestStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequestStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequestStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateRequestStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRequestStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateRequestStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *RideRequest           `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequestStatusResponse) Reset() {
	*x = UpdateRequestStatusResponse{}
	mi := &file_proto_v1_ride_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequestStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequestStatusResponse) ProtoMessage() {}

func (x *UpdateRequestStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequestStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateRequestStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateRequestStatusResponse) GetRequest() *RideRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type DeleteRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequestRequest) Reset() {
	*x = DeleteRequestRequest{}
	mi := &file_proto_v1_ride_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequestRequest) ProtoMessage() {}

func (x *DeleteRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequestRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteRequestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequestResponse) Reset() {
	*x = DeleteRequestResponse{}
	mi := &file_proto_v1_ride_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequestResponse) ProtoMessage() {}

func (x *DeleteRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequestResponse.ProtoReflect.Descriptor instead.
func (*DeleteRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteRequestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListNearbyRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GeohashPrefix string                 `protobuf:"bytes,1,opt,name=geohash_prefix,json=geohashPrefix,proto3" json:"geohash_prefix,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNearbyRequestsRequest) Reset() {
	*x = ListNearbyRequestsRequest{}
	mi := &file_proto_v1_ride_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNearbyRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNearbyRequestsRequest) ProtoMessage() {}

func (x *ListNearbyRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNearbyRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListNearbyRequestsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{22}
}

func (x *ListNearbyRequestsRequest) GetGeohashPrefix() string {
	if x != nil {
		return x.GeohashPrefix
	}
	return ""
}

func (x *ListNearbyRequestsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListNearbyRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*RideRequest         `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNearbyRequestsResponse) Reset() {
	*x = ListNearbyRequestsResponse{}
	mi := &file_proto_v1_ride_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNearbyRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNearbyRequestsResponse) ProtoMessage() {}

func (x *ListNearbyRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNearbyRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListNearbyRequestsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{23}
}

func (x *ListNearbyRequestsResponse) GetRequests() []*RideRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type ListMyRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyRequestsRequest) Reset() {
	*x = ListMyRequestsRequest{}
	mi := &file_proto_v1_ride_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyRequestsRequest) ProtoMessage() {}

func (x *ListMyRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListMyRequestsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{24}
}

func (x *ListMyRequestsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMyRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*RideRequest         `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyRequestsResponse) Reset() {
	*x = ListMyRequestsResponse{}
	mi := &file_proto_v1_ride_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyRequestsResponse) ProtoMessage() {}

func (x *ListMyRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ride_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListMyRequestsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_ride_proto_rawDescGZIP(), []int{25}
}

func (x *ListMyRequestsResponse) GetRequests() []*RideRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

var File_proto_v1_ride_proto protoreflect.FileDescriptor

const file_proto_v1_ride_proto_rawDesc = "" +
	"\n" +
	"\x13proto/v1/ride.proto\x12\bproto.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x01\n" +
	"\tRideOffer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x12\x19\n" +
	"\bfrom_geo\x18\x03 \x01(\tR\afromGeo\x12\x15\n" +
	"\x06to_geo\x18\x04 \x01(\tR\x05toGeo\x12\x12\n" +
	"\x04fare\x18\x05 \x01(\x01R\x04fare\x12.\n" +
	"\x04time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05seats\x18\a \x01(\x05R\x05seats\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"\xc6\x01\n" +
	"\vRideRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bfrom_geo\x18\x03 \x01(\tR\afromGeo\x12\x15\n" +
	"\x06to_geo\x18\x04 \x01(\tR\x05toGeo\x12.\n" +
	"\x04time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05seats\x18\x06 \x01(\x05R\x05seats\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\xa0\x01\n" +
	"\x12CreateOfferRequest\x12\x19\n" +
	"\bfrom_geo\x18\x01 \x01(\tR\afromGeo\x12\x15\n" +
	"\x06to_geo\x18\x02 \x01(\tR\x05toGeo\x12\x12\n" +
	"\x04fare\x18\x03 \x01(\x01R\x04fare\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05seats\x18\x05 \x01(\x05R\x05seats\"@\n" +
	"\x13CreateOfferResponse\x12)\n" +
	"\x05offer\x18\x01 \x01(\v2\x13.proto.v1.RideOfferR\x05offer\"!\n" +
	"\x0fGetOfferRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x10GetOfferResponse\x12)\n" +
	"\x05offer\x18\x01 \x01(\v2\x13.proto.v1.RideOfferR\x05offer\"f\n" +
	"\x12UpdateOfferRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04fare\x18\x02 \x01(\x01R\x04fare\x12\x14\n" +
	"\x05seats\x18\x03 \x01(\x05R\x05seats\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"@\n" +
	"\x13UpdateOfferResponse\x12)\n" +
	"\x05offer\x18\x01 \x01(\v2\x13.proto.v1.RideOfferR\x05offer\"$\n" +
	"\x12DeleteOfferRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13DeleteOfferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"V\n" +
	"\x17ListNearbyOffersRequest\x12%\n" +
	"\x0egeohash_prefix\x18\x01 \x01(\tR\rgeohashPrefix\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"G\n" +
	"\x18ListNearbyOffersResponse\x12+\n" +
	"\x06offers\x18\x01 \x03(\v2\x13.proto.v1.RideOfferR\x06offers\"+\n" +
	"\x13ListMyOffersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"C\n" +
	"\x14ListMyOffersResponse\x12+\n" +
	"\x06offers\x18\x01 \x03(\v2\x13.proto.v1.RideOfferR\x06offers\"\xa6\x01\n" +
	"\x14CreateRequestRequest\x12\x19\n" +
	"\bfrom_geo\x18\x01 \x01(\tR\afromGeo\x12\x15\n" +
	"\x06to_geo\x18\x02 \x01(\tR\x05toGeo\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05seats\x18\x04 \x01(\x05R\x05seats\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"H\n" +
	"\x15CreateRequestResponse\x12/\n" +
	"\arequest\x18\x01 \x01(\v2\x15.proto.v1.RideRequestR\arequest\"#\n" +
	"\x11GetRequestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x12GetRequestResponse\x12/\n" +
	"\arequest\x18\x01 \x01(\v2\x15.proto.v1.RideRequestR\arequest\"D\n" +
	"\x1aUpdateRequestStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"N\n" +
	"\x1bUpdateRequestStatusResponse\x12/\n" +
	"\arequest\x18\x01 \x01(\v2\x15.proto.v1.RideRequestR\arequest\"&\n" +
	"\x14DeleteRequestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteRequestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"X\n" +
	"\x19ListNearbyRequestsRequest\x12%\n" +
	"\x0egeohash_prefix\x18\x01 \x01(\tR\rgeohashPrefix\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"O\n" +
	"\x1aListNearbyRequestsResponse\x121\n" +
	"\brequests\x18\x01 \x03(\v2\x15.proto.v1.RideRequestR\brequests\"-\n" +
	"\x15ListMyRequestsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"K\n" +
	"\x16ListMyRequestsResponse\x121\n" +
	"\brequests\x18\x01 \x03(\v2\x15.proto.v1.RideRequestR\brequests2\xfd\a\n" +
	"\vRideService\x12L\n" +
	"\vCreateOffer\x12\x1c.proto.v1.CreateOfferRequest\x1a\x1d.proto.v1.CreateOfferResponse\"\x00\x12C\n" +
	"\bGetOffer\x12\x19.proto.v1.GetOfferRequest\x1a\x1a.proto.v1.GetOfferResponse\"\x00\x12L\n" +
	"\vUpdateOffer\x12\x1c.proto.v1.UpdateOfferRequest\x1a\x1d.proto.v1.UpdateOfferResponse\"\x00\x12L\n" +
	"\vDeleteOffer\x12\x1c.proto.v1.DeleteOfferRequest\x1a\x1d.proto.v1.DeleteOfferResponse\"\x00\x12[\n" +
	"\x10ListNearbyOffers\x12!.proto.v1.ListNearbyOffersRequest\x1a\".proto.v1.ListNearbyOffersResponse\"\x00\x12O\n" +
	"\fListMyOffers\x12\x1d.proto.v1.ListMyOffersRequest\x1a\x1e.proto.v1.ListMyOffersResponse\"\x00\x12R\n" +
	"\rCreateRequest\x12\x1e.proto.v1.CreateRequestRequest\x1a\x1f.proto.v1.CreateRequestResponse\"\x00\x12I\n" +
	"\n" +
	"GetRequest\x12\x1b.proto.v1.GetRequestRequest\x1a\x1c.proto.v1.GetRequestResponse\"\x00\x12d\n" +
	"\x13UpdateRequestStatus\x12$.proto.v1.UpdateRequestStatusRequest\x1a%.proto.v1.UpdateRequestStatusResponse\"\x00\x12R\n" +
	"\rDeleteRequest\x12\x1e.proto.v1.DeleteRequestRequest\x1a\x1f.proto.v1.DeleteRequestResponse\"\x00\x12a\n" +
	"\x12ListNearbyRequests\x12#.proto.v1.ListNearbyRequestsRequest\x1a$.proto.v1.ListNearbyRequestsResponse\"\x00\x12U\n" +
	"\x0eListMyRequests\x12\x1f.proto.v1.ListMyRequestsRequest\x1a .proto.v1.ListMyRequestsResponse\"\x00B\x11Z\x0f./proto/v1/rideb\x06proto3"

var (
	file_proto_v1_ride_proto_rawDescOnce sync.Once
	file_proto_v1_ride_proto_rawDescData []byte
)

func file_proto_v1_ride_proto_rawDescGZIP() []byte {
	file_proto_v1_ride_proto_rawDescOnce.Do(func() {
		file_proto_v1_ride_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_ride_proto_rawDesc), len(file_proto_v1_ride_proto_rawDesc)))
	})
	return file_proto_v1_ride_proto_rawDescData
}

var file_proto_v1_ride_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_v1_ride_proto_goTypes = []any{
	(*RideOffer)(nil),                   // 0: proto.v1.RideOffer
	(*RideRequest)(nil),                 // 1: proto.v1.RideRequest
	(*CreateOfferRequest)(nil),          // 2: proto.v1.CreateOfferRequest
	(*CreateOfferResponse)(nil),         // 3: proto.v1.CreateOfferResponse
	(*GetOfferRequest)(nil),             // 4: proto.v1.GetOfferRequest
	(*GetOfferResponse)(nil),            // 5: proto.v1.GetOfferResponse
	(*UpdateOfferRequest)(nil),          // 6: proto.v1.UpdateOfferRequest
	(*UpdateOfferResponse)(nil),         // 7: proto.v1.UpdateOfferResponse
	(*DeleteOfferRequest)(nil),          // 8: proto.v1.DeleteOfferRequest
	(*DeleteOfferResponse)(nil),         // 9: proto.v1.DeleteOfferResponse
	(*ListNearbyOffersRequest)(nil),     // 10: proto.v1.ListNearbyOffersRequest
	(*ListNearbyOffersResponse)(nil),    // 11: proto.v1.ListNearbyOffersResponse
	(*ListMyOffersRequest)(nil),         // 12: proto.v1.ListMyOffersRequest
	(*ListMyOffersResponse)(nil),        // 13: proto.v1.ListMyOffersResponse
	(*CreateRequestRequest)(nil),        // 14: proto.v1.CreateRequestRequest
	(*CreateRequestResponse)(nil),       // 15: proto.v1.CreateRequestResponse
	(*GetRequestRequest)(nil),           // 16: proto.v1.GetRequestRequest
	(*GetRequestResponse)(nil),          // 17: proto.v1.GetRequestResponse
	(*UpdateRequestStatusRequest)(nil),  // 18: proto.v1.UpdateRequestStatusRequest
	(*UpdateRequestStatusResponse)(nil), // 19: proto.v1.UpdateRequestStatusResponse
	(*DeleteRequestRequest)(nil),        // 20: proto.v1.DeleteRequestRequest
	(*DeleteRequestResponse)(nil),       // 21: proto.v1.DeleteRequestResponse
	(*ListNearbyRequestsRequest)(nil),   // 22: proto.v1.ListNearbyRequestsRequest
	(*ListNearbyRequestsResponse)(nil),  // 23: proto.v1.ListNearbyRequestsResponse
	(*ListMyRequestsRequest)(nil),       // 24: proto.v1.ListMyRequestsRequest
	(*ListMyRequestsResponse)(nil),      // 25: proto.v1.ListMyRequestsResponse
	(*timestamppb.Timestamp)(nil),       // 26: google.protobuf.Timestamp
}
var file_proto_v1_ride_proto_depIdxs = []int32{
	26, // 0: proto.v1.RideOffer.time:type_name -> google.protobuf.Timestamp
	26, // 1: proto.v1.RideRequest.time:type_name -> google.protobuf.Timestamp
	26, // 2: proto.v1.CreateOfferRequest.time:type_name -> google.protobuf.Timestamp
	0,  // 3: proto.v1.CreateOfferResponse.offer:type_name -> proto.v1.RideOffer
	0,  // 4: proto.v1.GetOfferResponse.offer:type_name -> proto.v1.RideOffer
	0,  // 5: proto.v1.UpdateOfferResponse.offer:type_name -> proto.v1.RideOffer
	0,  // 6: proto.v1.ListNearbyOffersResponse.offers:type_name -> proto.v1.RideOffer
	0,  // 7: proto.v1.ListMyOffersResponse.offers:type_name -> proto.v1.RideOffer
	26, // 8: proto.v1.CreateRequestRequest.time:type_name -> google.protobuf.Timestamp
	1,  // 9: proto.v1.CreateRequestResponse.request:type_name -> proto.v1.RideRequest
	1,  // 10: proto.v1.GetRequestResponse.request:type_name -> proto.v1.RideRequest
	1,  // 11: proto.v1.UpdateRequestStatusResponse.request:type_name -> proto.v1.RideRequest
	1,  // 12: proto.v1.ListNearbyRequestsResponse.requests:type_name -> proto.v1.RideRequest
	1,  // 13: proto.v1.ListMyRequestsResponse.requests:type_name -> proto.v1.RideRequest
	2,  // 14: proto.v1.RideService.CreateOffer:input_type -> proto.v1.CreateOfferRequest
	4,  // 15: proto.v1.RideService.GetOffer:input_type -> proto.v1.GetOfferRequest
	6,  // 16: proto.v1.RideService.UpdateOffer:input_type -> proto.v1.UpdateOfferRequest
	8,  // 17: proto.v1.RideService.DeleteOffer:input_type -> proto.v1.DeleteOfferRequest
	10, // 18: proto.v1.RideService.ListNearbyOffers:input_type -> proto.v1.ListNearbyOffersRequest
	12, // 19: proto.v1.RideService.ListMyOffers:input_type -> proto.v1.ListMyOffersRequest
	14, // 20: proto.v1.RideService.CreateRequest:input_type -> proto.v1.CreateRequestRequest
	16, // 21: proto.v1.RideService.GetRequest:input_type -> proto.v1.GetRequestRequest
	18, // 22: proto.v1.RideService.UpdateRequestStatus:input_type -> proto.v1.UpdateRequestStatusRequest
	20, // 23: proto.v1.RideService.DeleteRequest:input_type -> proto.v1.DeleteRequestRequest
	22, // 24: proto.v1.RideService.ListNearbyRequests:input_type -> proto.v1.ListNearbyRequestsRequest
	24, // 25: proto.v1.RideService.ListMyRequests:input_type -> proto.v1.ListMyRequestsRequest
	3,  // 26: proto.v1.RideService.CreateOffer:output_type -> proto.v1.CreateOfferResponse
	5,  // 27: proto.v1.RideService.GetOffer:output_type -> proto.v1.GetOfferResponse
	7,  // 28: proto.v1.RideService.UpdateOffer:output_type -> proto.v1.UpdateOfferResponse
	9,  // 29: proto.v1.RideService.DeleteOffer:output_type -> proto.v1.DeleteOfferResponse
	11, // 30: proto.v1.RideService.ListNearbyOffers:output_type -> proto.v1.ListNearbyOffersResponse
	13, // 31: proto.v1.RideService.ListMyOffers:output_type -> proto.v1.ListMyOffersResponse
	15, // 32: proto.v1.RideService.CreateRequest:output_type -> proto.v1.CreateRequestResponse
	17, // 33: proto.v1.RideService.GetRequest:output_type -> proto.v1.GetRequestResponse
	19, // 34: proto.v1.RideService.UpdateRequestStatus:output_type -> proto.v1.UpdateRequestStatusResponse
	21, // 35: proto.v1.RideService.DeleteRequest:output_type -> proto.v1.DeleteRequestResponse
	23, // 36: proto.v1.RideService.ListNearbyRequests:output_type -> proto.v1.ListNearbyRequestsResponse
	25, // 37: proto.v1.RideService.ListMyRequests:output_type -> proto.v1.ListMyRequestsResponse
	26, // [26:38] is the sub-list for method output_type
	14, // [14:26] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_v1_ride_proto_init() }
func file_proto_v1_ride_proto_init() {
	if File_proto_v1_ride_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_ride_proto_rawDesc), len(file_proto_v1_ride_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_ride_proto_goTypes,
		DependencyIndexes: file_proto_v1_ride_proto_depIdxs,
		MessageInfos:      file_proto_v1_ride_proto_msgTypes,
	}.Build()
	File_proto_v1_ride_proto = out.File
	file_proto_v1_ride_proto_goTypes = nil
	file_proto_v1_ride_proto_depIdxs = nil
}
